### ISSUE TITLE
Säve case

### ISSUE THREAD

**Issue by sunt05** [gusbacos/SUEWS_DB_Typology_test#1]
The EHC's modelled results could align closely with those from OHM after increasing the layer depths.
![1a3a554c-241f-4570-b0f3-01bebf2817c4](https://github.com/gusbacos/SUEWS_DB_Typology_test/assets/1802656/7af8e05b-0e09-4317-abb2-5bec17d12716)
![9499a33c-e8de-49d1-bf48-d4174d6063e9](https://github.com/gusbacos/SUEWS_DB_Typology_test/assets/1802656/aa2ac5bc-1f63-4b98-afbb-1b97429e4f98)

**Comment by sunt05** [comment]
code is here: https://github.com/gusbacos/SUEWS_DB_Typology_test/blob/test-local-suews/code/test-saave.ipynb

**Comment by biglimp** [comment]
1. I see that you multiplied k with 1.5. Any logical reason for that?
2. I updated with same values as used in Lindberg et al. 2020. The model becomes unstable and gives NaN for Qs. I updated the repo (master) for you to have a look. 
3. I will hunt down Frans to get the correct observed values for us to compare with also, as well as the correct settings used in the old original ESTM scheme.

**Comment by sunt05** [comment]
> 1. I see that you multiplied k with 1.5. Any logical reason for that?

That's just some testing - removing the modification of `k` should produce similar results.

> 2. I updated with same values as used in Lindberg et al. 2020. The model becomes unstable and gives NaN for Qs. I updated the repo (master) for you to have a look.

Will do - that's exactly what I'd like for the testing - thanks!

> 3. I will hunt down Frans to get the correct observed values for us to compare with also, as well as the correct settings used in the old original ESTM scheme.

Great!

**Comment by biglimp** [comment]
Ok, I checked with Frans and the correct values are now in the notebook on the master branch. It is taken from code 807 in ESTMcoefficients using 4 layers:
`Code	Surf_thick1	Surf_k1	Surf_rhoCp1	Surf_thick2	Surf_k2	Surf_rhoCp2	Surf_thick3	Surf_k3	Surf_rhoCp3	Surf_thick4	Surf_k4	Surf_rhoCp4	Surf_thick5	Surf_k5	Surf_rhoCp5
807	0.05	0.759	1860000	0.3	0.759	1860000	0.5	0.63	1200000	0.7	0.63	1200000	-999 -999 -999`

I tried with different settings but no luck on producing reasonable values in ECH. Only NaN after a few timesteps.

Observationdata are now also included (/SUEWS_DB_Typology_test/data/saveairport_base/Saeve_asphalt_QGmeasured.csv)

Your turn @sunt05

**Comment by sunt05** [comment]
Hi @biglimp, please follow the README to install a dev version of supy I just created for this - also check out the [test-save.ipynb](https://github.com/gusbacos/SUEWS_DB_Typology_test/blob/main/code/test-saave.ipynb) notebook.

**Comment by biglimp** [comment]
Installed new version of supy (2014.3.14.dev0) and used settings as in Lindberg et al. 2020. ECH still unstable. 

![image](https://github.com/gusbacos/SUEWS_DB_Typology_test/assets/11908356/f6fa234f-d87c-4fd4-be2d-8108bcafb9d1)

Can I ask you what you tried in order to fix this?

**Comment by sunt05** [comment]
Did you use the [test-save.ipynb](https://github.com/gusbacos/SUEWS_DB_Typology_test/blob/main/code/test-saave.ipynb) notebook? My tweaks are included there.

**Comment by biglimp** [comment]
but those number does not match up with lindberg et al. 2020

**Comment by sunt05** [comment]
The only change made was the layer depths, not specified in L20 and too thin for pavement - all other thermal properties remain unchanged.

**Comment by biglimp** [comment]
There are the values used in L20 for the airport:
`807	0.05	0.759	1860000	0.3	0.759	1860000	0.5	0.63	1200000	0.7	0.63	1200000	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	-999	!	Other roads		London	GLA`

I cannot see that k_surf and cp_surf in your notebook is coming from these numbers. is roads first seven values or 8 to 14?

I am not sure how to add the fifth layer but I just copied the 4th and made it different thickness, Didnt work, no matter what I tried.

**Comment by sunt05** [comment]
Got it - I thought these were part of the config files already and hence only modified the depth values, which clearly seemed unreasonable to me.

I'll explicitly set them in the Säve notebook and update you later and leaving some instructions there on configuration of ECH.

**Comment by biglimp** [comment]
Here is what I used. Please double-ckeck:

```python
# Setting correct ground layer parameters (807 from ESTM coefficients, used in Lindberg et al. 2020)
# EHC as heat storage scheme
df_state_ehc = df_state_init_a2.copy()
df_state_ehc.storageheatmethod = 5

# modify the depth of the vertical layers
ar_depth = np.repeat(np.array([[0.05, 0.3, 0.5, 0.7, 0.01]]), 7, axis=0).flatten()
df_state_ehc.loc[:, "dz_surf"] = ar_depth

# modify the heat capacity of the vertical layers
ar_cp = np.repeat(np.array([[1.86, 1.86, 1.2, 1.2, 1.2]])*1e6, 7, axis=0).flatten()
df_state_ehc.loc[:, "cp_surf"] = ar_cp

# modify the thermal conductivity of the vertical layers
ar_k = np.repeat(np.array([[0.759, 0.759, 0.63, 0.63, 0.63]]) , 7, axis=0).flatten()
df_state_ehc.loc[:, "k_surf"] = ar_k
```

**Comment by sunt05** [comment]
The only thing I'd like to change is the first layer depth (0.05 --> 0.1):

```python
# modify the depth of the vertical layers
ar_depth = np.repeat(np.array([[0.1, 0.3, 0.5, 0.7, 0.01]]), 7, axis=0).flatten()
df_state_ehc.loc[:, "dz_surf"] = ar_depth
```

With this change, things seems to work - please give it a go.

A thin layer closer to the imposed forcing could cause instability, a common issue with underlying heat conduction solvers; however, I believe this change is reasonable.

**Comment by biglimp** [comment]
Ok. Now we are getting close. I set frist layer thickness as close as possible to 0.05 to create a better 1:1 fit. The values gets a bit more scattered. Why do you think that is?

![image](https://github.com/gusbacos/SUEWS_DB_Typology_test/assets/11908356/1ce27827-a821-4490-b499-f5edd4f1209b)

![image](https://github.com/gusbacos/SUEWS_DB_Typology_test/assets/11908356/198105f2-5a4e-4f8e-acad-709b2caffc2a)

![image](https://github.com/gusbacos/SUEWS_DB_Typology_test/assets/11908356/8ab544a5-a60d-498d-be9f-14bce2f845f6)

On anther note. I am trying to put in regression line, equation and r2 but my old code does not work if you have nodata values. Du you have any suggestion/Code?

**Comment by sunt05** [comment]
The increased scattering from thinner first layers is likely tied to the numerical stability of the heat equation solver, a known limitation of similar algorithms.

This could be partially improved with some nontrivial tweaks; however, if adjusting the layer depth can bypass this issue, I suggest not putting excessive effort into the numerical solver.

**Comment by biglimp** [comment]
I had a closer look at the data and there is some time adjustments needed to be made in the observation datasets. It could be done more in detail but I think we have proven that the ECH is working fine. Suggest we close this issue and now move over to the coupling itself in SUEWS/SS.

![image](https://github.com/gusbacos/SUEWS_DB_Typology_test/assets/11908356/e0635429-7e0f-418d-9d1f-a0ef53f93d8d)

**Comment by sunt05** [comment]
Brilliant!
