### ISSUE TITLE
Unable to open Jupyter notebook run_tests

### ISSUE THREAD

**Issue by biglimp** [gusbacos/SUEWS_DB_Typology_test#4]
SInce I updated my repo, I cannot start my notebook run_tests.ipynb. Also, It cannot be visulised on the github webpage.

**Comment by sunt05** [comment]
Hopefully, it's been restored to your version now at https://github.com/gusbacos/SUEWS_DB_Typology_test/commit/9ebd2463198dc7e88b38b4874dbda5b02340d6c7. 
Feel free to reopen this if necessary.

**Comment by biglimp** [comment]
Works fine now. Thanks.
